### ISSUE TITLE
Hello, It's me again. With another question

### ISSUE THREAD

**Issue by marangachweya** [codersreign/blogpost-grid#1]
Hello @codersreign, 
I would like to ask a question please, When are you going to post your next video! Thank you, Because I enjoy coding them as projects and Learning new stuff every time about HTML and CSS  I watch a video of yours. Because I am not old enough to do it as a living so I just do it as an Interesting hobby when I don't have schoolwork (Mostly weekends).
Thank you!
Kind Regards.
Alvin Chweya (marangachweya)

**Comment by marangachweya** [comment]
Oh and I would also like to know when to expect new videos, Thanks again!

**Comment by codersreign** [comment]
Next video will be uploaded on this Sunday.

**Comment by marangachweya** [comment]
Ok thank you!
